# Generated by Django 3.1.7 on 2021-02-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('short_description', models.TextField(blank=True)),
                ('gender', models.CharField(choices=[('male', 'Samiec'), ('female', 'Samica')], max_length=7)),
                ('age', models.IntegerField()),
                ('accepts_cat', models.TextField(blank=True)),
                ('accepts_dogs', models.TextField(blank=True)),
                ('is_sterilised', models.BooleanField(default=False)),
                ('is_castrated', models.BooleanField(default=False)),
                ('is_vaccinated', models.BooleanField(default=False)),
                ('has_chip', models.BooleanField(default=False)),
            ],
        ),
    ]
