# Generated by Django 3.1.7 on 2021-02-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('male', 'Samiec'), ('female', 'Samica')], default='Default', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='name',
            field=models.CharField(db_index=True, default='Default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
