# Generated by Django 3.1.7 on 2021-02-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_auto_20210226_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='accepts_cat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='accepts_dogs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='age',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='has_chip',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='is_castrated',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='is_sterilised',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='is_vaccinated',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
